<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>RTG.ManualFocuser</RootNamespace>
    <AssemblyName>RTG.ManualFocuser</AssemblyName>
	  <TargetFolderName>Manual Focuser</TargetFolderName>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
	  <NoWarn>$(NoWarn);NU1701</NoWarn>
	  <NoWarn>$(NoWarn);CS0618</NoWarn>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NINA.Core" Version="3.2.0.9001" />
    <PackageReference Include="NINA.CustomControlLibrary" Version="3.2.0.9001" />
    <PackageReference Include="NINA.Equipment" Version="3.2.0.9001" />
    <PackageReference Include="NINA.Image" Version="3.2.0.9001" />
    <PackageReference Include="NINA.OxyPlot.Contrib.Wpf" Version="3.0.0.1001-preview3" />
    <PackageReference Include="NINA.Plugin" Version="3.2.0.9001" />
    <PackageReference Include="NINA.Profile" Version="3.2.0.9001" />
    <PackageReference Include="NINA.Sequencer" Version="3.2.0.9001" />
    <PackageReference Include="NINA.WPF.Base" Version="3.2.0.9001" />
    <PackageReference Include="NINACustomControlLibrary" Version="2.3.2.9001" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.Settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.Settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Sequence\" />
  </ItemGroup>
  <PropertyGroup />
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="&#xD;&#xA;if not exist &quot;%25localappdata%25\NINA\Plugins\3.0.0&quot; (&#xD;&#xA;  echo &quot;Creating $(PlatformName) Plugins folder&quot;&#xD;&#xA;  mkdir &quot;%25localappdata%25\NINA\Plugins\3.0.0&quot;&#xD;&#xA;)&#xD;&#xA;if not exist &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetFolderName)&quot; (&#xD;&#xA;  echo &quot;Creating $(PlatformName) Plugins $(TargetFolderName) folder&quot;&#xD;&#xA;  mkdir &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetFolderName)&quot;&#xD;&#xA;)&#xD;&#xA;&#xD;&#xA;echo &quot;Copying $(PlatformName) $(TargetFileName)&quot;&#xD;&#xA;xcopy &quot;$(TargetPath)&quot; &quot;%25localappdata%25\NINA\Plugins\3.0.0\$(TargetFolderName)&quot; /h/i/c/k/e/r/y&#xD;&#xA;  " />
  </Target>
</Project>